# Assignment

Import numpy as np

In [1]:
import numpy as np

Make a python list => \[1,2,3,4,5\]

Convert it into numpy array and print it

In [4]:
lst=[1,2,3,4,5]
np_arr=np.array(lst)
print(np_arr)

[1 2 3 4 5]


Make a python matrix (3 x 3) => \[[1,2,3],[4,5,6],[7,8,9]\]

Convert it into numpy array and print it

In [5]:
mat=[[1,2,3],[4,5,6],[7,8,9]]
np_arr1=np.array(mat)
print(np_arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

\[ [1,3,5],

 [7,9,11],
 
 [13,15,17] \]

In [7]:
mat1=np.arange(1,18,2).reshape(3,3)
print(mat1)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [22]:
np_arr2=np.random.randint(0,10,10)
np_arr2

array([7, 8, 8, 2, 1, 5, 3, 7, 1, 5])

Create numpy array => \[1,2,3,4,5\] and convert it to 2D array with 5 rows

In [31]:
np_arr3=np.array([1,2,3,4,5])
np_arr3.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

Print the shape of the above created array

In [29]:
np_arr3.shape

(5,)

Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [53]:
np_arr4=np.array(np.arange(0,10))
print(np_arr4[3])
print(np_arr4[4])
print(np_arr4[9])

3
4
9


Print alternate elements of that array

In [35]:
print(np_arr4[0::2])

[0 2 4 6 8]


Change last 3 elements into 100 using broadcasting and print

In [54]:
np_arr4[-3:]=0
np_arr4

array([0, 1, 2, 3, 4, 5, 6, 0, 0, 0])

Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.

In [48]:
mat2=np.array(np.arange(0,25)).reshape(5,5)
x,y=mat2.shape
m=int(x/2)-1
n=int(y/2)-1
mat2[m:m+3,n:n+3]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])